export const Books = [
  {
    key: 1,
    serial_no: 1,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    lang: "English",
    price: 19.99,
    sale_price: 15.99,
  },
  {
    key: 2,
    serial_no: 2,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    lang: "Spanish",
    price: 24.99,
    sale_price: 19.99,
  },
  {
    key: 3,
    serial_no: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    lang: "English",
    price: 16.99,
    sale_price: 13.99,
  },
  {
    key: 4,
    serial_no: 4,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    lang: "English",
    price: 29.99,
    sale_price: 23.99,
  },
];
